Website = "https://github.com/skoona/hubPower"

[Details]
  Icon = "internal/commons/resources/tools.png"
  Name = "Go APC Monitor"
  ID = "net.skoona.projects.hubPower"
  Version = "2.0.0"
  Build = 13
